Apps/Cliente/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views
from Apps.Cliente.views import ClienteCreate, Login, home, salir, mascotas
from django.contrib.auth import login
from django.views.generic import TemplateView
from Apps.Mascota.views import MascotaCreate, PetList,PetUpdate, PetDelete,PetListR , PetListAll,PetConfir, PetGallery,PetGalleryA,PetGalleryR
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required

urlpatterns = [
     
    url(r'^ingresar$', Login.as_view(), name='login'),
    url(r'^mascotas$', login_required(PetGallery.as_view()), name="listarD"),
    url(r'^listarA$', login_required(PetGalleryA.as_view()), name='listarAa'),
    url(r'^listarR$', login_required(PetGalleryR.as_view()), name='listarR'),
    url(r'^salir$', views.salir ,name='salir'),
    url(r'^$', views.home, name='home' ),
    url(r'^registrarM$', login_required(MascotaCreate.as_view()), name='registrarM'),
    url(r'^listarM$', login_required(PetList.as_view()), name='listarM'),
    url(r'^listar$', login_required(PetListR.as_view()), name='listarRr'),  
    url(r'^listarAll$', login_required(PetListAll.as_view()), name='listarAll'), 
    url(r'^ModificarM/(?P<pk>\d+)/$', login_required(PetUpdate.as_view()), name='ModificarM'),
    url(r'^EliminarM/(?P<pk>\d+)/$', login_required(PetDelete.as_view()), name='EliminarM'),
    url(r'^confirmar/(?P<pk>\d+)/$', login_required(PetConfir.as_view()), name='confirmar'),
    #url(r'^$', TemplateView.as_view(template_name = 'baseLogin.html'), name='home'),

    #path('', views.home, name='home'),


    path('registroCliente/', views.ClienteCreate.as_view(),
    name = 'registroCli' ),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/Mascota/urls.py
from django.urls import path
from django.conf.urls import url, include
from . import views
from Apps.Mascota.views import MascotaCreate
from django.contrib.auth import login
from django.views.generic import TemplateView

urlpatterns = [
     
    
    



    
]

MisPerrisDjango/urls.py
from django.contrib import admin
from django.urls import path, include
from Apps.Cliente import urls
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',include('Apps.Cliente.urls')),
   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Apps/Cliente/models.py
from django.db import models

# asdCreate your models here.
class Cliente (models.Model):
    email = models.CharField(max_length = 30, null = True, blank = True)
    run = models.CharField(max_length = 30)
    clave = models.CharField(max_length = 30, null = True, blank = True)
    nombre = models.CharField(max_length= 50)
    fecha_nac = models.DateField()
    Movil = models.CharField(max_length = 30)
    vivienda = models.CharField(max_length = 30, null = True, blank = True)

Apps/Mascota/models.py
from django.db import models

# Create your models here.

class Mascota(models.Model):
    nombre = models.CharField(max_length = 50)
    foto = models.ImageField(upload_to='upload/')
    raza = models.CharField(max_length = 50)
    descripcion = models.CharField(max_length = 255)
    estado = models.CharField( max_length=15)
    objects = models.Manager()

Apps/Cliente/forms.py
from django import forms
from .models import Cliente
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from Apps.Mascota.models import Mascota
from django.contrib.auth.models import User

class ClienteForm(UserCreationForm):

    class Meta:
        model = User
        
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            
        ]

        labels = {
            'username': 'Nombre de usuario',
            'first_name': 'Nombre',
            'last_name': 'Apellidos',
            'email': 'Email',
            'password1':'Ingrese Clave',
            'password2': 'Confirme Clave',
        }

        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control'}),
    		'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
    		'email': forms.TextInput(attrs={'class':'form-control'}),
    		'password1': forms.PasswordInput(attrs={'class':'form-control'}),
            'password2': forms.PasswordInput(attrs={'class':'form-control'}),
            
        }

class FormularioLogin(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super(FormularioLogin, self).__init__(*args, **kwargs)        
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].widget.attrs['placeholder'] = 'Ingrese Nombre'       
        self.fields['password'].widget.attrs['class'] = 'form-control'
        self.fields['password'].widget.attrs['placeholder'] = 'Ingrese Clave'


estado_list = [
    ('adoptado','ADOPTADO'),
    ('rescatado', 'RESCATADO'),
    ('disponible','DISPONIBLE'),
]

class MascotaForm(forms.ModelForm):
    class Meta:
        model = Mascota
        
        fields = [
            'nombre',
            'foto',
            'raza',
            'descripcion',
            'estado',
            

        ]

        labels = {
            'nombre': 'Nombre',
            'foto': 'Foto',
            'raza': 'Raza',
    		'descripcion': 'Descripcion', 
    		'estado': 'Estado', 
    		
        }

        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}),
    		'foto': forms.FileInput,
            'raza': forms.TextInput(attrs={'class':'form-control'}),
    		'descripcion': forms.Textarea(attrs={'class':'form-control'}),
    		'estado': forms.Select(choices=estado_list), 
    		
        }

Apps/Cliente/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from .models import Cliente
from django.views.generic import CreateView, ListView, FormView
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.urls import reverse_lazy
from .forms import ClienteForm, FormularioLogin
from django.contrib.auth import authenticate, login, logout
from django.template import RequestContext
from Apps.Mascota.models import Mascota

from django.contrib.auth.models import User
# Create your views here.

def home (request):
    return render(request, 'index.html', {})

def inde (request):
    return render(request, 'login.html', {})

def salir(request):
    logout(request)
    return render(request, 'index.html', {})

def mascotas(request):
    return render(request, 'mascotas.html', {})

def listar (request):
    return render(request, 'listarPet.html', {})

def adoptar(request):
    return render(request, 'Confirmar.html', {})

# Create your views here.
class Login(FormView):
    #Establecemos la plantilla a utilizar
    template_name = 'login.html'
    #Le indicamos que el formulario a utilizar es el formulario de autenticación de Django
    form_class = FormularioLogin
    #Le decimos que cuando se haya completado exitosamente la operación nos redireccione a la url bienvenida de la aplicación personas
    success_url = ('mascotas')
 
    def dispatch(self, request, *args, **kwargs):
        #Si el usuario está autenticado entonces nos direcciona a la url establecida en success_url
        if request.user.is_authenticated:
            return HttpResponseRedirect(self.get_success_url())
        #Sino lo está entonces nos muestra la plantilla del login simplemente
        else:
            return super(Login, self).dispatch(request, *args, **kwargs)
 
    def form_valid(self, form):
        login(self.request, form.get_user())
        return super(Login, self).form_valid(form)


class ClienteCreate(CreateView):
    model = User
    form_class = ClienteForm
    template_name = 'registro.html'
    success_url = reverse_lazy('home')

Apps/Mascota/views.py
from django.shortcuts import render
from django.views.generic import UpdateView, CreateView, ListView, FormView, DeleteView
from Apps.Cliente.views import home, listar, mascotas
from Apps.Mascota.models import Mascota
from Apps.Cliente.forms import MascotaForm
from django.urls import reverse_lazy
import os


# Create your views here.




class PetListR(ListView):
    model= Mascota
    form_class=  MascotaForm   
    template_name= 'listarPet.html'

    def get_queryset(self):
            return Mascota.objects.filter(estado='rescatado')

class PetListAll(ListView):
    model= Mascota
    form_class=  MascotaForm   
    template_name= 'listarPet.html'



class MascotaCreate(CreateView):
    model = Mascota
    form_class = MascotaForm
    template_name = 'homePet.html'
    success_url = reverse_lazy('listarD')
    
class PetList(ListView):
    model= Mascota
    form_class=  MascotaForm   
    template_name= 'listarPet.html'

    def get_queryset(self):
            return Mascota.objects.filter(estado='disponible')

class PetUpdate(UpdateView):
    model= Mascota
    form_class = MascotaForm
    template_name= 'ModPet.html'
    success_url = reverse_lazy('listarM')

class PetDelete(DeleteView):
    model= Mascota
    template_name= 'eliminarPet.html'
    success_url = reverse_lazy('listarAll')

class PetGallery(ListView):
    model= Mascota
    form_class=  MascotaForm   
    template_name= 'mascotas.html'

    def get_queryset(self):
            return Mascota.objects.filter(estado='disponible')

class PetGalleryR(ListView):
    model= Mascota
    form_class=  MascotaForm   
    template_name= 'mascotas.html'

    def get_queryset(self):
            return Mascota.objects.filter(estado='rescatado')


class PetGalleryA(ListView):
    model= Mascota
    form_class=  MascotaForm   
    template_name= 'mascotas.html'

    def get_queryset(self):
            return Mascota.objects.filter(estado='adoptado')

class PetConfir(DeleteView):
    model= Mascota
    template_name= 'Confirmar.html'
    success_url = reverse_lazy('listarD')

Apps/Cliente/templates/Confirmar.html
{% extends 'mascotas.html '%}


{% block content %}
<form class="form-horizontal" method="POST" action="">
    {% csrf_token %}
    <h1>¿Desea adoptar a {{ object.nombre }}?</h1>
    <button class="btn btn_danger" type="submit">Confirmar</button>
    <a class="btn btn-default" href="{% url 'listarM' %}">Cancelar</a>
</form>

{% endblock %}

Apps/Cliente/templates/ModPet.html
{% extends 'mascotas.html' %}

{% block content %}
        <form class="form-horizontal" method="POST" action="">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">     	
                        <div class="col-md-2">{{ field.label_tag }}</div>
                        <div class="clearfix"></div>
                        <div class="col-md-2">{{ field }}</div>
                        <div class="clearfix"></div>
                        {% if field.errors %}
                      <div class="row">
                        <div class="label label-danger col-md-2">
                          {{ field.errors  }}
                </div>
                </div>
                    {% endif %}
                    </div>
                {% endfor %}
                        <input type="submit" value="Modificar">
        </form>
{% endblock %}

Apps/Cliente/templates/eliminarPet.html
{% extends 'mascotas.html' %}

{% block content %}
        <form class="form-horizontal" method="POST" action="">
                {% csrf_token %}
                <h1>¿Desea eliminar el registro de {{ object.nombre }}?</h1>
                <button class="btn btn_danger" type="submit">Confirmar</button>
                <a class="btn btn-default" href="{% url 'listarAll' %}">Cancelar</a>
        </form>
{% endblock %}

Apps/Cliente/templates/homePet.html
{% extends 'mascotas.html' %}

{% block content %}
    <form class="form" method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
            <div class="form-group">     	
                <div class="col-md-2">{{ field.label_tag }}</div>
                <div class="clearfix"></div>
                <div class="col-md-2">{{ field }}</div>
                <div class="clearfix"></div>
                {% if field.errors %}
              <div class="row">
                <div class="label label-danger col-md-2">
                  {{ field.errors  }}
        </div>
        </div>
            {% endif %}
            </div>
        {% endfor %}
                <input type="submit" value="Grabar">
                
        </form>
{% endblock %}

Apps/Cliente/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <link href="{% static 'css/style.css'%}" rel="stylesheet">
        <link rel="stylesheet" href="" crossorigin="anonymous">
        <script src= {% static 'js/jquery-3.3.1.slim.min.js'%}> </script>
        <script src= {% static 'js/popper.min.js'%}> </script>
        <script src= {% static 'js/bootstrap.min.js'%}> </script>
        <title>Mis Perris</title>
        <script src={% static 'js/hes-gallery.js' %} ></script>
        <script src={% static 'css/hes-gallery.css' %} ></script>
        <!--fin galeria-->
        <link rel="shortcut icon" href="#" />
    </head>
    <body id="bod">
        <header class="container1" id="top">  
            <div class="img">
                <img src="{% static 'imagenes/img/logo.png' %}" alt=""/>
            </div>
            <div class="menu-mobile">
                <a href="javascript:void(0)"><span class="fa fa-bars" aria-hidden="true"></span></a>
            </div>
            <nav class="main-menu displayed" style="display: none;">
                <ul>
                    <li><a href="#">Inicio</a></li>
                    <li><a href="#">¿Quienes somos?</a></li>
                    <li><a href="#">Servicios</a></li>
                    <li><a href="#">Contáctos</a></li>
                    <li><a href="{% url 'registroCli' %}">Registrar</a></li>
                    <li><a href="{% url 'login' %}">Ingresar</a></li>
                </ul>
            </nav>
        </header>    
        <!--carrusel -->
        <div class="wrap">
            <header class="botones">
                <label for="slide-1-trigger"><span style="color:white">O</span></label>
                <label for="slide-2-trigger"><span style="color:white">O</span></label>
                <label for="slide-3-trigger"><span style="color:white">O</span></label>
            </header>
            <input id="slide-1-trigger" type="radio" name="slides" checked>
            <section class="slide slide-one">
                <h1>Con apolo estamos muy feliz en casa ahora</h1>
            </section>
            <input id="slide-2-trigger" type="radio" name="slides">
            <section class="slide slide-two">
                <h1>Duque a sido una gran compania desde que lo tengo</h1>
            </section>
            <input id="slide-3-trigger" type="radio" name="slides">
            <section class="slide slide-three">
                <h1>Tom es un gran compañero en el da a día</h1>
            </section>
        </div>
        <!--fin carrusel-->
        <!--rescate-->
        <div  class="red1">
            <img src="{% static 'imagenes/img/redes.png' %}" alt=""/>
        </div>
        <div id="tit" ><h2>RESCATE</h2>
            <h5>ETAPA UNO</h5>
            <hr  />
            <p >Rescatamos perros en situación de peligro y/o abandono.
                Los rehabilitamos y los preparamos para buscarles un hogar.</p>
            <img src={% static 'imagenes/img/rescate.jpg' %} alt=""/>
        </div>
        <div id="tit2">
            <img class="img-responsive" src={% static 'imagenes/img/crowfunding.jpg' %} alt="" />
            <h2>CROWDFUNDING</h2>
            <h5>FINANCIAMIENTO</h5>
            <hr   />
            <p class="font-size-18">Sigue nuestras redes sociales para informarte acerca de las
                diversas campañas y actividades que realizamos para obtener financiamiento para seguir ayudando.</p>
        </div>
        <div class="pl-3">
            <strong><a id="cam" href="#">CAMPAÑAS</a></strong>
        </div>
        <!--fin rescate-->
        <!--    galeria-->
<div class="hes-gallery margen-top">
            <img src={% static 'imagenes/rescatados/Bigotes_tn.jpg' %} alt="image1" data-fullsize={% static "imagenes/rescatados/Bigotes.jpg" %} data-subtext='Bigote es un fiel amigo'  data-alt="piesiak" class="margin">
            <img src={% static "imagenes/rescatados/Chocolate_tn.jpg" %} alt="image2" data-fullsize={% static "imagenes/rescatados/Chocolate.jpg" %} data-subtext='Chocolate es un loquillo'  data-alt="piesiak" class="margin">
            <img src={% static "imagenes/rescatados/Luna_tn.jpg" %} alt="image3" data-fullsize= {% static "imagenes/rescatados/Luna.jpg" %} data-subtext='Luna es lo mejor que nos pudo pasar'  data-alt="piesiak" class="margin">
            <img src={% static "imagenes/rescatados/Maya_tn.jpg" %} alt="image4" data-fullsize={% static "imagenes/rescatados/Maya.jpg" %} data-subtext='Maya es muy tierna'  data-alt="piesiak" class="margin">
            <img src={% static "imagenes/rescatados/Oso_tn.jpg" %} alt="image5" data-fullsize={% static "imagenes/rescatados/Oso.jpg" %} data-subtext='Oso es lo mas jugueton que hay'  data-alt="piesiak" class="margin">
            <img src={% static "imagenes/rescatados/Pexel_tn.jpg" %} alt="image6" data-fullsize={% static "imagenes/rescatados/Pexel.jpg" %} data-subtext='Pexel es tan fotogenico'  data-alt="piesiak" class="margin">
            <img src={% static "imagenes/rescatados/Wifi_tn.jpg" %} alt="image7" data-fullsize={% static "imagenes/rescatados/Wifi.jpg" %} data-subtext='Wifi le gusta navegar'  data-alt="piesiak" class="margin">
        </div>
        <!--    fin galeria-->
    </body>
</html>

Apps/Cliente/templates/listarPet.html
{% extends 'mascotas.html' %}
{% block extrahead %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% endblock %}
{% block content%}
<div class="container">
        {% if object_list %}
        {% for mascota in object_list %}
        <div id="products" class="view-group">
                    <div class="item col-xs-4 col-lg-4">
                        <div class="thumbnail card">
                            <div class="img-event">
                                <img class="group list-group-image img-fluid" src="{{ mascota.foto.url}}" width="150"  alt="" />
                            </div>
                            <div class="caption card-body">
                                <h4 class="group card-title inner list-group-item-heading">
                                        {{ mascota.nombre}}</h4>
                                <p class="group inner list-group-item-text">
                                        {{ mascota.descripcion}}</p>
                                <div class="row">
                                    <div class="col-xs-12 col-md-6">
                                        <p class="lead">
                                                {{ mascota.raza}}</p>
                                    </div>
                                    <div class="col-xs-12 col-md-6">
                                            <p class="lead">
                                                    {{ mascota.estado }}</p>
                                        </div>
                                </div>
                                {% if perms.Mascota.add_mascota %}   
                                <a class="btn btn-success" href="{% url 'ModificarM' mascota.id %}">Modificar</a>
                                <a class="btn btn-success" href="{% url 'EliminarM' mascota.id %}">Eliminar</a>
                                {% endif %}
                                <a class="btn btn-success" href="{% url 'confirmar' mascota.id %}">Adoptar</a>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% endif %}
    </div>
{% endblock %}

Apps/Cliente/templates/login.html
{% load staticfiles %}
<!DOCTYPE <!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Mis Perris</title>
    <link rel="stylesheet" href="" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css" />
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'js/jquery.min.js' %}" rel="stylesheet">
</head>

<body>
    <header class="container1" id="top">
        <div class="img">
            <img src="{% static 'imagenes/img/logo.png' %}" alt="" />
        </div>
        <div class="menu-mobile">
            <a href="javascript:void(0)"><span class="fa fa-bars" aria-hidden="true"></span></a>
        </div>
        <nav class="main-menu displayed" style="display: none;">
            <ul>
                <li><a href="{% url 'home' %}">Inicio</a></li>
                <li><a href="#">¿Quienes somos?</a></li>
                <li><a href="#">Servicios</a></li>
                <li><a href="#">Contáctos</a></li>
                <li><a href="{% url 'registroCli' %}">Registrar</a></li>
                <li><a href="{% url 'login' %}">Ingresar</a></li>
            </ul>
        </nav>
    </header>
    <section class="login-block">

    <div class="row1">
            <h2>Bienvenido a Mis Perris</h2>
            <p>Mis Perris es un centro de animales rescatados, enfocados en encontrarle un nuevo hogar</p>
    </div>    

        <div class="container">
            <div class="row">
                <div class="col-md-4 login-sec">
                    <h2 class="text-center">Ingrese Datos</h2>
                    <form role="form" method="post" id='form_login'>
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="text">Usuario:</label>
                            {{ form.username }}
                        </div>
                        <div class="form-group">
                            <label class="text">Contraseña:</label>
                            {{ form.password }}
                        </div>
                        <button class="btn btn-lg btn-success btn-block" type="submit" name="login">Ingresar</button>
                    </form>
                </div>
                <div >
                    
                </div>
            </div>
    </section>
</body>

</html>

Apps/Cliente/templates/mascotas.html
{% load staticfiles %}
<!DOCTYPE <!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Administración Mascotas</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <script src="{% static 'js/gallery.js'%}"></script>
    <link href="{% static 'css/style.css'%}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
     <link href="{% static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link href="{% static 'css/list.css'%}" rel="stylesheet">
    {% block extrahead %}
    {% endblock %}
</head>
<body>
        {% block header %}
        <header class="container1" id="top">  
                <div class="img">
                    <img src="{% static 'imagenes/img/logo.png' %}" alt=""/>
                </div>
                <div class="menu-mobile">
                    <a href="javascript:void(0)"><span class="fa fa-bars" aria-hidden="true"></span></a>
                </div>
                <nav class="main-menu displayed" style="display: none;">
                    <ul>
                        <li><a href="{% url 'listarAa' %}">Inicio</a></li>   
                        {% if perms.Mascota.add_mascota %}                    
                        <li><a href="{% url 'registrarM' %}">Agregar</a></li>
                        <li><a href="{% url 'listarRr' %}">Listar Rescatados</a></li>
                        <li><a href="{% url 'listarAll' %}">Listar Todos</a></li>
                        {% endif %}
                        <li><a href="{% url 'listarM' %}">Listar Disponibles</a></li>                       
                        <li><a href="{% url 'salir' %}">Cerrar sesión</a></li>                       
                    </ul>
                </nav>
            </header>
        {% endblock %}
        {% block content%}
       
             <div class="container">
                <div class="row" style=" margin:20px">  
                  <div class="col-xs-12">                    
                      <a class="btn btn-small btn-danger" href="{% url 'listarAa' %}" >
                            Adoptados
                      </a>
                      <a class="btn btn-small btn-danger"  href="{% url 'listarD' %}">
                            Disponibles
                      </a>
                      <a class="btn btn-small btn-danger"  href="{% url 'listarR' %}">
                            Rescatados
                      </a>
                  </div>
                </div>  
                
                           
                          {% if object_list %}
                          {% for mascota in object_list %}
                          <div class="col-md-4" data-tag='Disponibles'>
                             <img src="{{ mascota.foto.url}}" class="img-responsive" alt="img" width="150">
                          </div>
                          {% endfor %}
                         {% endif %}                                                                                                                                                         
                  
                  
      </div>
            
            
            
            
        
        {% endblock %}
    
    
</body>
</html>

Apps/Cliente/templates/registro.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Formulario</title>
    <link href="{% static 'css/style.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.17.0/dist/jquery.validate.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>
  <body >
    <header class="container1" id="top">  
      <div class="img">
          <img src="{% static 'imagenes/img/logo.png' %}" alt=""/>
      </div>
      <div class="menu-mobile">
          <a href="javascript:void(0)"><span class="fa fa-bars" aria-hidden="true"></span></a>
      </div>
      <nav class="main-menu displayed" style="display: none;">
          <ul>
              <li><a href="{% url 'home' %}">Inicio</a></li>
              <li><a href="#">¿Quienes somos?</a></li>
              <li><a href="#">Servicios</a></li>
              <li><a href="#">Contáctos</a></li>             
          </ul>
      </nav>
    </header>
        <form class="form-group" method="POST" action="">
            {% csrf_token %}
            {% for field in form %}
            <div class="form-group">     	
                <div class="col-md-2">{{ field.label_tag }}</div>
                <div class="clearfix"></div>
                <div class="col-md-2">{{ field }}</div>
                <div class="clearfix"></div>
                {% if field.errors %}
                <div class="row">
                <div class="label label-danger col-md-2">
                {{ field.errors  }}
                </div>
                 </div>
            {% endif %}
          </div>
            {% endfor %}
              <input type="submit" value="Grabar">
      </form>
          </tbody>
        </table>
     </div>
<script src="js/validar.js" type="text/javascript"></script>
  </body>
</html>